// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'generate-parent-item'
  | 'pig-prefs-api-key-label'
  | 'pig-prefs-auto-item-type'
  | 'pig-prefs-base-url-label'
  | 'pig-prefs-forced-itemtype-label'
  | 'pig-prefs-itemtype-header'
  | 'pig-prefs-llm-header'
  | 'pig-prefs-model-label'
  | 'pig-prefs-prompts-header'
  | 'pig-prefs-system-prompt-label'
  | 'pig-prefs-test-btn'
  | 'pig-prefs-user-prompt-label';
